name    'nvpuppet-polipo'
version '1.1.0'
source 'git://github.com/nvalentine-puppetlabs/puppet-polipo.git'
author 'nathan@puppetlabs.com'
license 'Apache License, Version 2.0'
summary 'Install and configure polipo caching web proxy.'
description 'Install and configure polipo caching web proxy.'
project_page 'http://github.com/nvalentine-puppetlabs/puppet-polipo'

dependency 'puppetlabs/stdlib', '4.1.0'
